### ISSUE TITLE
`MultiColumnTextViewEx` brutal caching

### ISSUE THREAD

**Issue by ointeractive-depot** [suwhs/wATLlib#6]
I've spend a lot of time to solve the problem when text size don't changed, and understand that it's take part with some kind of caching or something like this, after project build I need to reload an application several times when font size changed. There's no any other libraries which behave so like this.

**Comment by suwhs** [comment]
hmm, there is no persistent caching,  (font size changes forces layout invalidation). Can you provide minimum project to reproduce this?

**Comment by ointeractive-depot** [comment]
Well, I'm at `1.4.5b` now, but problem exists still. Now my project almost same as your ViewPager activity (https://github.com/suwhs/wATL/blob/master/app/src/main/java/su/whs/watl/samples/ViewPagerActivity.java), so you can use your own code to reproduce it if you need. I need to set text size programmaticaly (`mPager.getOptions ().setTextSize (25)`)

**Comment by ointeractive-depot** [comment]
Seems you was able to reproduce it?)

**Comment by suwhs** [comment]
found crash in layout calculation thread, fixed

**Comment by ointeractive-depot** [comment]
Wow, sounds great! What version number does it have now?

**Comment by suwhs** [comment]
wATLlib version: 1.4.6a 
(repo up-to-date)

**Comment by ointeractive-depot** [comment]
Awesome, thank you! But I prefer to use a Gradle to have a new versions.

**Comment by suwhs** [comment]
compile 'su.whs:wATLlib:1.4.6a'

**Comment by ointeractive-depot** [comment]
Yes, I know it, thanks)
